using System.ComponentModel.DataAnnotations;

namespace SajhaSikshya.Data.Enums;

/// <summary>
/// Category of an in-app/real-time notification, used to pick an icon, group
/// notifications in the UI, and route delivery (e.g. via <see cref="Hubs.NotificationHub"/>).
/// </summary>
public enum NotificationType
{
    /// <summary>A new direct message from another user.</summary>
    [Display(Name = "Message", Description = "A new direct message from another user.")]
    Message = 0,

    /// <summary>An update related to an order (placed, confirmed, ready, completed, cancelled).</summary>
    [Display(Name = "Order", Description = "An update related to one of your orders.")]
    Order = 1,

    /// <summary>A new review or rating was left.</summary>
    [Display(Name = "Review", Description = "A new review or rating was left.")]
    Review = 2,

    /// <summary>An update on student verification status.</summary>
    [Display(Name = "Verification", Description = "An update on your student verification status.")]
    Verification = 3,

    /// <summary>A system-generated notice (maintenance, policy, account).</summary>
    [Display(Name = "System", Description = "A system-generated notice.")]
    System = 4,

    /// <summary>A personalized recommendation generated by the AI assistant.</summary>
    [Display(Name = "AI Recommendation", Description = "A personalized recommendation generated by the AI assistant.")]
    AIRecommendation = 5,

    /// <summary>A platform-wide announcement from administrators.</summary>
    [Display(Name = "Announcement", Description = "A platform-wide announcement from administrators.")]
    Announcement = 6,

    /// <summary>An update on a marketplace listing's moderation status (approved, rejected, archived, restored).</summary>
    [Display(Name = "Listing", Description = "An update on one of your marketplace listings.")]
    Listing = 7,
}
